name: Ship js prepare
on:
  workflow_dispatch
jobs:
  build:
    name: Prepare release
    runs-on: ubuntu-latest
    if: ${{ github.ref_name }} == 'main'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main
      - uses: actions/setup-node@v3
        with:
          node-version: 16.14.0
          cache: 'npm'
      - run: |
          npm ci
      - run: npm run release -- --yes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
